sudo: false
language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    hexo
script: 
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: hexo
  local-dir: public